[package]
name = "ffmpeg_egui_hlw"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = "0.33.3"
env_logger = "0.11.8"
log = "0.4.29"
rfd = "0.16.0"
tokio = "1.48.0"
